### PR TITLE
Extract constructor from mixin to class.

### PR DESCRIPTION
**Pull request by marshall-lee**
Hello!
The reason that it's not convenient to use pipeline operator with custom callable classes.
`Dry::Pipeline::Mixin` should bring no functionality other than `>>` operator.

### CODE REVIEW

**Comment by marshall-lee** [comment]
/cc @solnic: if it's gonna be merged, you should fix gem `transflow` [here](https://github.com/solnic/transflow/blob/19ccef1bb497dbedb60c73bc6b0a3ff6d7023704/lib/transflow/transaction.rb#L19).
For now it's the only gem on RubyGems which depends on `dry-pipeline` according to rubygems reverse_dependencies API: https://rubygems.org/api/v1/gems/dry-pipeline/reverse_dependencies.json

**Comment by nepalez** [comment]
:+1:

**Comment by AMHOL** [comment]
:+1:

**Comment by janraasch** [comment]
:+1:

**Comment by marshall-lee** [comment]
@solnic, @AMHOL maybe merge it and release? please :)

**Comment by davydovanton** [comment]
:+1:

**Comment by thesunwave** [comment]
:+1:

**Comment by marshall-lee** [comment]
Another good case why it matters:

``` ruby
class Something
  extend Dry::Pipeline::Mixin

  def self.call(a)
    new(a).call
  end

  def initialize(a)
    @a = a
  end

  def call
    # ...
  end
end

Something >> AnotherThing
```

**Comment by marshall-lee** [comment]
@AMHOL thanks!

**Comment by AMHOL** [comment]
@marshall-lee NP, released 0.0.2

**Pull request merged**
